config/routes.rb
Spree::Core::Engine.add_routes do
  namespace :admin do
    resources :templates do
      # get 'templates'
    end
  end
end

app/controllers/spree/admin/templates_controller.rb
module Spree
  module Admin
    class TemplatesController < Spree::Admin::BaseController
      def index
        @dirs = Dir['app/views/spree/**/**.erb']
        render :index
      end

      #TODO - different actions
      def show

        if params[:id] == 'templates_list'
          dirs1 = Dir['app/views/spree/**/**.erb'].map{|path| path.gsub('app/views/spree/', '')}
          dirs2 = Dir["#{store_path}**/**.erb"].map{|path| path.gsub(store_path, '')}
          @dirs = ([''] + dirs1 + dirs2).uniq.sort
          render :templates_list, :layout => false
        elsif params[:id] == 'page'
          if File.exists?(store_path + params[:page])
            render text: open(store_path + params[:page]).read
          else
            render text: open('app/views/spree/' + params[:page]).read
          end
        end
      end

      def update
        template_name = store_path + params[:template]
        FileUtils.mkdir_p(File.dirname(template_name))
        File.open(template_name, 'w') { |file| file.write(params[:source]) }

        render text: ''
      end

      private
        def store_path
          "app/views/stores/#{params[:code]}/spree/"
        end
    end
  end
end

app/helpers/spree/templates_helper.rb
module Spree
  module TemplatesHelper

  end
end

app/views/spree/admin/shared/_templates_sidebar_menu.erb
<%# if can? :admin, Spree::Template %>
<ul class="nav nav-sidebar">
  <%= tab nil, url: spree.admin_templates_url, icon: 'list-alt', label: "Templates" %>
</ul>
<%# end %>

app/views/spree/admin/templates/index.html.erb
<div class="row">
  <div class="col-md-3">
    <%= select_tag :domain,
      options_for_select([''] + Spree::Store.all.map{|a|[a.name,a.code]}),
        class: "form-control select-domain" %>
  </div>
</div>
<div class="row">
  <div class="templates-list col-md-6">
  </div>
</div>

<div class="edititng hidden">
  <textarea rows="15" cols="150" name="page" class="source form-control">


  </textarea>
  <br>
  <div class="btn btn-success save-editing">
    Save
  </div>
</div>



<!-- TODO move to special file -->
<script type="text/javascript">
  function getDomainCode() {
    return $('.select-domain').find(":selected").attr('value');
  }

  $('.select-domain').change(function(e){
    $.get( "<%= admin_template_path('templates_list') %>?code="+getDomainCode(), function( data ) {
      $('.edititng').addClass('hidden');
      $('.templates-list').html(data)

      $('.templates-list select').change(function(e){
        $('.source').parent().addClass('hidden')
        page = $('.templates-list select').find(":selected").attr('value');
        $.get( "<%= admin_template_path('page') %>?code="+getDomainCode() + "&page=" + page, function( data ) {
          console.log(data)
          $('.source').val(data);
          $('.source').parent().removeClass('hidden')
        })
      })
    });
  })

  $('.save-editing').click(function(e){
    template = $('.templates-list select').find(":selected").attr('value');
    $.ajax({
      type: 'PUT',
      url: '<%= admin_template_path('update') %>',
      data: {source: $('.source').val(), code: getDomainCode(), template: template},
    })
  })
</script>

app/views/spree/admin/templates/templates_list.html.erb
<%= select_tag :domain, options_for_select(@dirs), class: "form-control select-domain" %>